# Generated by Django 3.2 on 2021-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='header',
            field=models.CharField(default='', max_length=255),
        ),
    ]
