# Generated by Django 3.2 on 2021-06-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210608_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='link',
        ),
    ]
