# Generated by Django 3.2 on 2021-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='para',
            field=models.TextField(default=''),
        ),
    ]
