# Generated by Django 3.2 on 2021-06-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_para'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='para',
        ),
    ]
