# Generated by Django 3.2 on 2021-06-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
